// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateRequest struct {
	Uid    int64  `json:"uid"`
	Pid    int64  `json:"pid"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Id     int64  `json:"id"`
	Uid    int64  `json:"uid"`
	Pid    int64  `json:"pid"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type ListRequest struct {
	Uid uint64 `json:"uid"`
}

type ListResponse struct {
	Data  []*DetailResponse `json:"data"`
	Total int64             `json:"total"`
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
	Result string `json:"result"`
}

type UpdateRequest struct {
	Id     int64  `json:"id"`
	Uid    int64  `json:"uid,optional"`
	Pid    int64  `json:"pid,optional"`
	Amount uint64 `json:"amount,optional"`
	Status uint64 `json:"status,optional"`
}

type UpdateResponse struct {
	Id     int64  `json:"id"`
	Uid    int64  `json:"uid"`
	Pid    int64  `json:"pid"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}
