// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"mall/service/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order/create",
				Handler: CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/detail",
				Handler: DetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/list",
				Handler: ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/remove",
				Handler: RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/order/update",
				Handler: UpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
