// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: rpc/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Stock         uint64                 `protobuf:"varint,3,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Amount        uint64                 `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Status        uint64                 `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_rpc_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateRequest) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateRequest) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_rpc_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 产品修改
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Stock         uint64                 `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Amount        uint64                 `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Status        uint64                 `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_rpc_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateRequest) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateRequest) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Stock         uint64                 `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Amount        uint64                 `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Status        uint64                 `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_rpc_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *UpdateResponse) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateResponse) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateResponse) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 产品删除
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_rpc_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_rpc_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// 产品详情
type DetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailRequest) Reset() {
	*x = DetailRequest{}
	mi := &file_rpc_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailRequest) ProtoMessage() {}

func (x *DetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailRequest.ProtoReflect.Descriptor instead.
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return file_rpc_product_proto_rawDescGZIP(), []int{6}
}

func (x *DetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Stock         uint64                 `protobuf:"varint,4,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Amount        uint64                 `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Status        uint64                 `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResponse) Reset() {
	*x = DetailResponse{}
	mi := &file_rpc_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResponse) ProtoMessage() {}

func (x *DetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResponse.ProtoReflect.Descriptor instead.
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return file_rpc_product_proto_rawDescGZIP(), []int{7}
}

func (x *DetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetailResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *DetailResponse) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *DetailResponse) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DetailResponse) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_rpc_product_proto protoreflect.FileDescriptor

const file_rpc_product_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/product.proto\x12\aproduct\"}\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Desc\x18\x02 \x01(\tR\x04Desc\x12\x14\n" +
	"\x05Stock\x18\x03 \x01(\x04R\x05Stock\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x04R\x06Amount\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x04R\x06Status\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8d\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Desc\x18\x03 \x01(\tR\x04Desc\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\x04R\x05Stock\x12\x16\n" +
	"\x06Amount\x18\x05 \x01(\x04R\x06Amount\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\x04R\x06Status\"\x8e\x01\n" +
	"\x0eUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Desc\x18\x03 \x01(\tR\x04Desc\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\x04R\x05Stock\x12\x16\n" +
	"\x06Amount\x18\x05 \x01(\x04R\x06Amount\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\x04R\x06Status\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"(\n" +
	"\x0eDeleteResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\tR\x06Result\"\x1f\n" +
	"\rDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x01\n" +
	"\x0eDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Desc\x18\x03 \x01(\tR\x04Desc\x12\x14\n" +
	"\x05Stock\x18\x04 \x01(\x04R\x05Stock\x12\x16\n" +
	"\x06Amount\x18\x05 \x01(\x04R\x06Amount\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\x04R\x06Status2\xf5\x01\n" +
	"\aProduct\x129\n" +
	"\x06Create\x12\x16.product.CreateRequest\x1a\x17.product.CreateResponse\x129\n" +
	"\x06Update\x12\x16.product.UpdateRequest\x1a\x17.product.UpdateResponse\x129\n" +
	"\x06Delete\x12\x16.product.DeleteRequest\x1a\x17.product.DeleteResponse\x129\n" +
	"\x06Detail\x12\x16.product.DetailRequest\x1a\x17.product.DetailResponseB\vZ\t./productb\x06proto3"

var (
	file_rpc_product_proto_rawDescOnce sync.Once
	file_rpc_product_proto_rawDescData []byte
)

func file_rpc_product_proto_rawDescGZIP() []byte {
	file_rpc_product_proto_rawDescOnce.Do(func() {
		file_rpc_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_product_proto_rawDesc), len(file_rpc_product_proto_rawDesc)))
	})
	return file_rpc_product_proto_rawDescData
}

var file_rpc_product_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_product_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: product.CreateRequest
	(*CreateResponse)(nil), // 1: product.CreateResponse
	(*UpdateRequest)(nil),  // 2: product.UpdateRequest
	(*UpdateResponse)(nil), // 3: product.UpdateResponse
	(*DeleteRequest)(nil),  // 4: product.DeleteRequest
	(*DeleteResponse)(nil), // 5: product.DeleteResponse
	(*DetailRequest)(nil),  // 6: product.DetailRequest
	(*DetailResponse)(nil), // 7: product.DetailResponse
}
var file_rpc_product_proto_depIdxs = []int32{
	0, // 0: product.Product.Create:input_type -> product.CreateRequest
	2, // 1: product.Product.Update:input_type -> product.UpdateRequest
	4, // 2: product.Product.Delete:input_type -> product.DeleteRequest
	6, // 3: product.Product.Detail:input_type -> product.DetailRequest
	1, // 4: product.Product.Create:output_type -> product.CreateResponse
	3, // 5: product.Product.Update:output_type -> product.UpdateResponse
	5, // 6: product.Product.Delete:output_type -> product.DeleteResponse
	7, // 7: product.Product.Detail:output_type -> product.DetailResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_product_proto_init() }
func file_rpc_product_proto_init() {
	if File_rpc_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_product_proto_rawDesc), len(file_rpc_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_product_proto_goTypes,
		DependencyIndexes: file_rpc_product_proto_depIdxs,
		MessageInfos:      file_rpc_product_proto_msgTypes,
	}.Build()
	File_rpc_product_proto = out.File
	file_rpc_product_proto_goTypes = nil
	file_rpc_product_proto_depIdxs = nil
}
