// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type CreateRequest struct {
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  uint64 `json:"stock"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type DeleteResponse struct {
	Result string `json:"result"`
}

type DeleteResquest struct {
	Id int64 `json:"id"`
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  uint64 `json:"stock"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type UpdateRequest struct {
	Id     int64  `json:"id"`
	Name   string `json:"name,optional"`
	Desc   string `json:"desc,optional"`
	Stock  uint64 `json:"stock"`
	Amount uint64 `json:"amount,optional"`
	Status uint64 `json:"status,optional"`
}

type UpdateResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Desc   string `json:"desc"`
	Stock  uint64 `json:"stock"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}
