// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Realname string `json:"realname"`
	Gender   int64  `json:"gender"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Realname string `json:"realname"`
	Gender   int64  `json:"gender"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Realname string `json:"realname"`
	Gender   int64  `json:"gender"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
}
